name: docker-build-push

on:
  workflow_dispatch:

  push:
    branches:
      - 'unstable'

jobs:
  docker-build-push:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to  docker hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and publish image
        env:
          # fork friendly ^^
          DOCKER_REPO: docker.io/${{ secrets.docker_username }}/kvrocks-operator
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --label "org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/kvrocks-operator" \
          --label "org.opencontainers.image.description=kvrocks-operator image" \
          --label "org.opencontainers.image.licenses=MIT" \
          --push \
          -t ${DOCKER_REPO}:latest \
          -f Dockerfile \
          .
